FROM arvindr226/alpine-ssh

ARG DEPLOY_SCRIPTS_DIR=./ci-tools

ADD ${DEPLOY_SCRIPTS_DIR} /opt/${DEPLOY_SCRIPTS_DIR}
WORKDIR /opt/${DEPLOY_SCRIPTS_DIR}

RUN ["chmod", "+x", "update-image.sh"]
RUN ["chmod", "+x", "init-deployment.sh"]

ENTRYPOINT ["bin/bash" "ci-tools/init-deployment.sh"]